# Generated by Django 5.2.8 on 2026-08-13 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name_sr', models.CharField(max_length=120)),
                ('name_en', models.CharField(blank=True, max_length=120)),
                ('name_fr', models.CharField(blank=True, max_length=120)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'gallery categories',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('title_sr', models.CharField(max_length=255)),
                ('title_en', models.CharField(blank=True, max_length=255)),
                ('title_fr', models.CharField(blank=True, max_length=255)),
                ('excerpt_sr', models.TextField()),
                ('excerpt_en', models.TextField(blank=True)),
                ('excerpt_fr', models.TextField(blank=True)),
                ('body_sr', models.TextField(help_text='Paragrafi odvojeni praznim redom.')),
                ('body_en', models.TextField(blank=True)),
                ('body_fr', models.TextField(blank=True)),
                ('image_url', models.URLField(max_length=500)),
                ('published_at', models.DateField()),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-published_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('url', models.URLField(max_length=500)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_sr', models.CharField(max_length=200)),
                ('title_en', models.CharField(blank=True, max_length=200)),
                ('title_fr', models.CharField(blank=True, max_length=200)),
                ('description_sr', models.TextField(blank=True)),
                ('description_en', models.TextField(blank=True)),
                ('description_fr', models.TextField(blank=True)),
                ('source', models.CharField(choices=[('youtube', 'YouTube'), ('instagram', 'Instagram'), ('local', 'Lokalno')], max_length=20)),
                ('thumb_url', models.URLField(max_length=500)),
                ('youtube_id', models.CharField(blank=True, max_length=32)),
                ('instagram_url', models.URLField(blank=True, max_length=500)),
                ('local_src', models.URLField(blank=True, max_length=500)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', '-id'],
            },
        ),
        migrations.CreateModel(
            name='GallerySubcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('name_sr', models.CharField(max_length=120)),
                ('name_en', models.CharField(blank=True, max_length=120)),
                ('name_fr', models.CharField(blank=True, max_length=120)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='website.gallerycategory')),
            ],
            options={
                'verbose_name_plural': 'gallery subcategories',
                'ordering': ['order', 'id'],
                'unique_together': {('category', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_sr', models.CharField(max_length=200)),
                ('title_en', models.CharField(blank=True, max_length=200)),
                ('title_fr', models.CharField(blank=True, max_length=200)),
                ('image_url', models.URLField(max_length=500)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='website.gallerysubcategory')),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
