# Generated by Django 5.2.8 on 2026-08-20 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_contactmessage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ['order', '-id'], 'verbose_name': 'projekat', 'verbose_name_plural': 'projekti'},
        ),
        migrations.AddField(
            model_name='video',
            name='category',
            field=models.CharField(choices=[('event', 'Događaj'), ('show', 'Emisija'), ('interview', 'Intervju'), ('promo', 'Promo'), ('social', 'Društvene mreže'), ('special', 'Specijalni projekat')], default='event', max_length=20),
        ),
        migrations.AddField(
            model_name='video',
            name='year',
            field=models.PositiveIntegerField(default=2026),
        ),
    ]
